### ISSUE TITLE
Struct can be stored on the heap

### ISSUE THREAD

**Issue by noah0316** [jrasmusson/ios-professional-course#2]
- https://github.com/jrasmusson/ios-professional-course/blob/main/Knowing/StackVsHeap/README.md

Thank you for useful explanation of reference, value type in swift!!🥳

I created issue because I think some contents need to be added.

When ReferenceType owned ValueType, ValueType is stored on the heap 

The following is an example code.

```swift
import Foundation

struct ValueType {
    var member1: Int
    var member2: Int
}

class ReferenceType {
    var member1: Int
    var member2: Int
    var value: ValueType
    
    init(member1: Int, member2: Int) {
        self.member1 = member1
        self.member2 = member2
        self.value = ValueType(member1: member1 + 1, member2: member2 + 1)
    }
}

func test() {
    var ref1 = ReferenceType(member1: 9, member2: 3)

    withUnsafePointer(to: &ref1) {
        print("ref1 address: \($0)")
    }
    
    withUnsafePointer(to: &ref1.value) {
        print("ref1.value address: \($0)")
    }
}

test()
```

![StackHeap](https://user-images.githubusercontent.com/63908856/176199132-fd9f3ba4-faed-4459-aa4c-fb610be1e764.png)

If you check the memory area you can see that the ValueType is stored on the heap

thank you for reading it!

**Comment by jrasmusson** [comment]
Hi Noah. Excellent point.

You are correct. Structs can be stored on heaps when they are included in closures. 

With this post I wanted to emphasize the difference between classes and structs. And give students a reason for why knowing the difference is important. 

But you are 100% correct. And I love that you looked into the memory map to prove it :)

Thank you for sharing.

**Comment by noah0316** [comment]
@jrasmusson I sincerely appreciate your reply 
Thank you!!
